# Generated by Django 4.0.5 on 2022-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=7)),
                ('cost_usd', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('cost_rub', models.FloatField()),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
